#!/usr/bin/env python3
"""
BVR Precision Engagement Controller with Hardware Verification

Ensures BVR precision engagements only proceed when all required
hardware subsystems are verified and operational.

Hardware verification gates:
- GPS timing synchronization verified
- RF propagation sensors calibrated
- Antenna patterns validated
- Datalink connectivity confirmed
- Weapon system ready state verified
"""

import numpy as np
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple, Callable
from enum import Enum, auto
import time as pytime
import threading
from queue import Queue


class HardwareComponent(Enum):
    """Hardware subsystems requiring verification"""
    GPS_TIMING = auto()
    RF_SENSORS = auto()
    ANTENNA_ARRAY = auto()
    DATALINK = auto()
    WEAPON_SYSTEM = auto()
    TRACKING_PROCESSOR = auto()
    EW_SUITE = auto()
    POWER_MANAGEMENT = auto()


class VerificationStatus(Enum):
    """Verification state for hardware components"""
    UNVERIFIED = auto()
    VERIFYING = auto()
    VERIFIED = auto()
    FAILED = auto()
    DEGRADED = auto()


@dataclass
class HardwareVerificationResult:
    """Result of a hardware verification check"""
    component: HardwareComponent
    status: VerificationStatus
    timestamp: float
    error_code: Optional[int] = None
    error_message: Optional[str] = None
    degradation_percent: float = 0.0


@dataclass
class HardwareVerificationState:
    """
    Tracks verification state for all hardware components

    All components must be VERIFIED before BVR engagement is authorized.
    """
    components: Dict[HardwareComponent, HardwareVerificationResult] = field(default_factory=dict)
    last_full_verification: float = 0.0
    verification_valid_duration: float = 300.0  # 5 minutes

    def __post_init__(self):
        # Initialize all components as UNVERIFIED
        current_time = pytime.time()
        for component in HardwareComponent:
            self.components[component] = HardwareVerificationResult(
                component=component,
                status=VerificationStatus.UNVERIFIED,
                timestamp=current_time
            )

    def update_component(self, result: HardwareVerificationResult):
        """Update verification status for a component"""
        self.components[result.component] = result

        # Check if all components are now verified
        if all(r.status == VerificationStatus.VERIFIED for r in self.components.values()):
            self.last_full_verification = result.timestamp

    def is_fully_verified(self, current_time: Optional[float] = None) -> bool:
        """Check if all hardware is verified and verification is current"""
        if current_time is None:
            current_time = pytime.time()

        # Check verification age
        if current_time - self.last_full_verification > self.verification_valid_duration:
            return False

        # Check all components
        return all(r.status == VerificationStatus.VERIFIED for r in self.components.values())

    def get_unverified_components(self) -> List[HardwareComponent]:
        """Get list of components that are not verified"""
        return [
            comp for comp, result in self.components.items()
            if result.status != VerificationStatus.VERIFIED
        ]

    def get_failed_components(self) -> List[Tuple[HardwareComponent, str]]:
        """Get list of failed components with error messages"""
        return [
            (comp, result.error_message or "Unknown error")
            for comp, result in self.components.items()
            if result.status == VerificationStatus.FAILED
        ]


class EngagementAuthorization(Enum):
    """Authorization states for BVR engagement"""
    NOT_AUTHORIZED = auto()
    PENDING_VERIFICATION = auto()
    AUTHORIZED = auto()
    AUTHORIZED_DEGRADED = auto()
    DENIED_HW_FAILURE = auto()


@dataclass
class EngagementRequest:
    """Request to execute a BVR precision engagement"""
    request_id: str
    target_track_id: int
    target_position: np.ndarray
    target_velocity: np.ndarray
    estimated_cep: float  # Circular Error Probable (meters)
    weapon_type: str
    timestamp: float


@dataclass
class EngagementAuthorizationResult:
    """Result of engagement authorization check"""
    request: EngagementRequest
    authorization: EngagementAuthorization
    hw_verification_state: HardwareVerificationState
    reason: str
    authorized_at: Optional[float] = None


@dataclass
class HardwareMonitorAlert:
    """Alert generated by continuous hardware monitoring"""
    component: HardwareComponent
    severity: str  # 'INFO', 'WARNING', 'CRITICAL'
    timestamp: float
    message: str
    current_value: float
    threshold_value: float


class ContinuousHardwareMonitor:
    """
    Continuous hardware health monitoring during engagement

    Monitors all hardware subsystems in real-time and generates alerts
    on degradation or failure. Automatically triggers re-verification
    and abort recommendations when critical thresholds are exceeded.
    """

    def __init__(self, controller: 'BVREngagementController'):
        self.controller = controller
        self.monitoring_active = False
        self.monitor_thread: Optional[threading.Thread] = None
        self.alert_queue: Queue = Queue()
        self.alert_callbacks: List[Callable[[HardwareMonitorAlert], None]] = []

        # Monitoring intervals (seconds)
        self.gps_timing_interval = 1.0  # Check every second
        self.rf_calibration_interval = 30.0  # Check every 30s
        self.antenna_health_interval = 5.0  # Check every 5s
        self.datalink_quality_interval = 2.0  # Check every 2s
        self.tracking_latency_interval = 0.5  # Check every 500ms
        self.power_reserve_interval = 5.0  # Check every 5s

        # Last check timestamps
        self.last_checks: Dict[HardwareComponent, float] = {}

        # Alert thresholds (trigger warnings before failure)
        self.gps_timing_warning_ns = 15.0  # Warn at 15ns, fail at 20ns
        self.antenna_warning_percent = 1.5  # Warn at 1.5%, fail at 2%
        self.power_warning_percent = 18.0  # Warn at 18%, fail at 15%

    def register_alert_callback(self, callback: Callable[[HardwareMonitorAlert], None]):
        """Register callback to receive monitoring alerts"""
        self.alert_callbacks.append(callback)

    def start_monitoring(self):
        """Start continuous hardware monitoring"""
        if self.monitoring_active:
            return

        self.monitoring_active = True
        self.monitor_thread = threading.Thread(target=self._monitor_loop, daemon=True)
        self.monitor_thread.start()

    def stop_monitoring(self):
        """Stop continuous hardware monitoring"""
        self.monitoring_active = False
        if self.monitor_thread:
            self.monitor_thread.join(timeout=2.0)

    def _monitor_loop(self):
        """Main monitoring loop (runs in background thread)"""
        current_time = pytime.time()

        # Initialize last check times
        for component in HardwareComponent:
            self.last_checks[component] = current_time

        while self.monitoring_active:
            current_time = pytime.time()

            # Check each component at its designated interval
            if current_time - self.last_checks[HardwareComponent.GPS_TIMING] >= self.gps_timing_interval:
                self._check_gps_timing()
                self.last_checks[HardwareComponent.GPS_TIMING] = current_time

            if current_time - self.last_checks[HardwareComponent.RF_SENSORS] >= self.rf_calibration_interval:
                self._check_rf_calibration()
                self.last_checks[HardwareComponent.RF_SENSORS] = current_time

            if current_time - self.last_checks[HardwareComponent.ANTENNA_ARRAY] >= self.antenna_health_interval:
                self._check_antenna_health()
                self.last_checks[HardwareComponent.ANTENNA_ARRAY] = current_time

            if current_time - self.last_checks[HardwareComponent.DATALINK] >= self.datalink_quality_interval:
                self._check_datalink_quality()
                self.last_checks[HardwareComponent.DATALINK] = current_time

            if current_time - self.last_checks[HardwareComponent.TRACKING_PROCESSOR] >= self.tracking_latency_interval:
                self._check_tracking_latency()
                self.last_checks[HardwareComponent.TRACKING_PROCESSOR] = current_time

            if current_time - self.last_checks[HardwareComponent.POWER_MANAGEMENT] >= self.power_reserve_interval:
                self._check_power_reserve()
                self.last_checks[HardwareComponent.POWER_MANAGEMENT] = current_time

            # Sleep briefly to avoid busy-waiting
            pytime.sleep(0.1)

    def _generate_alert(self, component: HardwareComponent, severity: str,
                       message: str, current_value: float, threshold_value: float):
        """Generate and distribute monitoring alert"""
        alert = HardwareMonitorAlert(
            component=component,
            severity=severity,
            timestamp=pytime.time(),
            message=message,
            current_value=current_value,
            threshold_value=threshold_value
        )

        self.alert_queue.put(alert)

        # Call registered callbacks
        for callback in self.alert_callbacks:
            try:
                callback(alert)
            except Exception as e:
                print(f"Alert callback error: {e}")

    def _check_gps_timing(self):
        """Monitor GPS timing drift"""
        result = self.controller.hw_state.components.get(HardwareComponent.GPS_TIMING)
        if not result:
            return

        # In real system, would query actual GPS timing error from hardware
        # For simulation, check if component is verified
        if result.status == VerificationStatus.FAILED:
            self._generate_alert(
                HardwareComponent.GPS_TIMING,
                'CRITICAL',
                'GPS timing synchronization FAILED',
                0.0, 20.0
            )
        elif result.status == VerificationStatus.VERIFIED:
            # Check if approaching warning threshold (simulated)
            if result.timestamp < pytime.time() - 30:  # Stale data
                self._generate_alert(
                    HardwareComponent.GPS_TIMING,
                    'WARNING',
                    'GPS timing data is stale - re-verification recommended',
                    0.0, 0.0
                )

    def _check_rf_calibration(self):
        """Monitor RF sensor calibration validity"""
        result = self.controller.hw_state.components.get(HardwareComponent.RF_SENSORS)
        if not result:
            return

        calibration_age = pytime.time() - result.timestamp

        if calibration_age > 300:  # 5 minutes
            self._generate_alert(
                HardwareComponent.RF_SENSORS,
                'CRITICAL',
                'RF sensor calibration expired - recalibrate immediately',
                calibration_age, 300.0
            )
        elif calibration_age > 240:  # 4 minutes (warning before failure)
            self._generate_alert(
                HardwareComponent.RF_SENSORS,
                'WARNING',
                'RF sensor calibration expiring soon - recalibrate recommended',
                calibration_age, 240.0
            )

    def _check_antenna_health(self):
        """Monitor antenna array element health"""
        result = self.controller.hw_state.components.get(HardwareComponent.ANTENNA_ARRAY)
        if not result:
            return

        if result.status == VerificationStatus.DEGRADED:
            self._generate_alert(
                HardwareComponent.ANTENNA_ARRAY,
                'WARNING',
                f'Antenna array degraded: {result.degradation_percent:.1f}% element failure',
                result.degradation_percent, 2.0
            )
        elif result.status == VerificationStatus.FAILED:
            self._generate_alert(
                HardwareComponent.ANTENNA_ARRAY,
                'CRITICAL',
                f'Antenna array FAILED: {result.degradation_percent:.1f}% element failure exceeds limit',
                result.degradation_percent, 2.0
            )

    def _check_datalink_quality(self):
        """Monitor weapon datalink quality in real-time"""
        result = self.controller.hw_state.components.get(HardwareComponent.DATALINK)
        if not result:
            return

        if result.status == VerificationStatus.DEGRADED:
            self._generate_alert(
                HardwareComponent.DATALINK,
                'WARNING',
                f'Datalink quality degraded: {100.0 - result.degradation_percent:.0f}% link quality',
                100.0 - result.degradation_percent, 90.0
            )
        elif result.status == VerificationStatus.FAILED:
            self._generate_alert(
                HardwareComponent.DATALINK,
                'CRITICAL',
                'Datalink connectivity LOST - mid-course guidance unavailable',
                0.0, 70.0
            )

    def _check_tracking_latency(self):
        """Monitor tracking processor latency"""
        result = self.controller.hw_state.components.get(HardwareComponent.TRACKING_PROCESSOR)
        if not result:
            return

        if result.status == VerificationStatus.FAILED:
            self._generate_alert(
                HardwareComponent.TRACKING_PROCESSOR,
                'CRITICAL',
                'Tracking processor latency exceeded - track quality degraded',
                0.0, 120.0
            )

    def _check_power_reserve(self):
        """Monitor power management reserves"""
        result = self.controller.hw_state.components.get(HardwareComponent.POWER_MANAGEMENT)
        if not result:
            return

        if result.status == VerificationStatus.FAILED:
            self._generate_alert(
                HardwareComponent.POWER_MANAGEMENT,
                'CRITICAL',
                'Power reserves CRITICAL - load shedding may be required',
                0.0, 15.0
            )

    def get_pending_alerts(self) -> List[HardwareMonitorAlert]:
        """Retrieve all pending alerts from queue"""
        alerts = []
        while not self.alert_queue.empty():
            alerts.append(self.alert_queue.get())
        return alerts


class BVREngagementController:
    """
    Controls BVR precision engagements with mandatory hardware verification

    CRITICAL: No engagement is authorized without verified hardware state.

    Verification Requirements:
    - GPS timing: < 20ns RMS synchronization error
    - RF sensors: Calibrated within last 5 minutes
    - Antenna array: All elements operational (< 2% failure)
    - Datalink: Connectivity confirmed to weapon
    - Weapon system: Ready state confirmed
    - Tracking processor: Latency < 120ms
    - EW suite: Operational
    - Power management: Adequate reserves
    """

    # Engagement thresholds
    MAX_GPS_TIMING_ERROR_NS = 20.0
    MAX_ANTENNA_ELEMENT_FAILURE_PERCENT = 2.0
    MAX_TRACKING_LATENCY_MS = 120.0
    MIN_POWER_RESERVE_PERCENT = 15.0
    MAX_CEP_FOR_PRECISION_M = 100.0

    def __init__(self):
        self.hw_state = HardwareVerificationState()
        self.pending_requests: Dict[str, EngagementRequest] = {}
        self.authorization_log: List[EngagementAuthorizationResult] = []
        self.continuous_monitor = ContinuousHardwareMonitor(self)

    def verify_gps_timing(self, timing_error_ns: float) -> HardwareVerificationResult:
        """Verify GPS timing synchronization"""
        current_time = pytime.time()

        if timing_error_ns <= self.MAX_GPS_TIMING_ERROR_NS:
            result = HardwareVerificationResult(
                component=HardwareComponent.GPS_TIMING,
                status=VerificationStatus.VERIFIED,
                timestamp=current_time
            )
        else:
            result = HardwareVerificationResult(
                component=HardwareComponent.GPS_TIMING,
                status=VerificationStatus.FAILED,
                timestamp=current_time,
                error_code=1001,
                error_message=f"GPS timing error {timing_error_ns:.1f}ns exceeds {self.MAX_GPS_TIMING_ERROR_NS}ns limit"
            )

        self.hw_state.update_component(result)
        return result

    def verify_rf_sensors(self, calibration_valid: bool, last_calibration_time: float) -> HardwareVerificationResult:
        """Verify RF sensor calibration"""
        current_time = pytime.time()

        calibration_age = current_time - last_calibration_time

        if calibration_valid and calibration_age < 300.0:  # 5 minutes
            result = HardwareVerificationResult(
                component=HardwareComponent.RF_SENSORS,
                status=VerificationStatus.VERIFIED,
                timestamp=current_time
            )
        else:
            result = HardwareVerificationResult(
                component=HardwareComponent.RF_SENSORS,
                status=VerificationStatus.FAILED,
                timestamp=current_time,
                error_code=1002,
                error_message=f"RF sensor calibration invalid or stale (age: {calibration_age:.0f}s)"
            )

        self.hw_state.update_component(result)
        return result

    def verify_antenna_array(self, element_failure_percent: float) -> HardwareVerificationResult:
        """Verify antenna array element status"""
        current_time = pytime.time()

        if element_failure_percent <= self.MAX_ANTENNA_ELEMENT_FAILURE_PERCENT:
            result = HardwareVerificationResult(
                component=HardwareComponent.ANTENNA_ARRAY,
                status=VerificationStatus.VERIFIED,
                timestamp=current_time
            )
        elif element_failure_percent <= 5.0:  # Degraded but operational
            result = HardwareVerificationResult(
                component=HardwareComponent.ANTENNA_ARRAY,
                status=VerificationStatus.DEGRADED,
                timestamp=current_time,
                degradation_percent=element_failure_percent
            )
        else:
            result = HardwareVerificationResult(
                component=HardwareComponent.ANTENNA_ARRAY,
                status=VerificationStatus.FAILED,
                timestamp=current_time,
                error_code=1003,
                error_message=f"Antenna element failure {element_failure_percent:.1f}% exceeds limits"
            )

        self.hw_state.update_component(result)
        return result

    def verify_datalink(self, connectivity_confirmed: bool, link_quality_percent: float) -> HardwareVerificationResult:
        """Verify datalink connectivity to weapon"""
        current_time = pytime.time()

        if connectivity_confirmed and link_quality_percent >= 90.0:
            result = HardwareVerificationResult(
                component=HardwareComponent.DATALINK,
                status=VerificationStatus.VERIFIED,
                timestamp=current_time
            )
        elif connectivity_confirmed and link_quality_percent >= 70.0:
            result = HardwareVerificationResult(
                component=HardwareComponent.DATALINK,
                status=VerificationStatus.DEGRADED,
                timestamp=current_time,
                degradation_percent=100.0 - link_quality_percent
            )
        else:
            result = HardwareVerificationResult(
                component=HardwareComponent.DATALINK,
                status=VerificationStatus.FAILED,
                timestamp=current_time,
                error_code=1004,
                error_message=f"Datalink connectivity: {connectivity_confirmed}, quality: {link_quality_percent:.0f}%"
            )

        self.hw_state.update_component(result)
        return result

    def verify_weapon_system(self, ready_state: bool, self_test_passed: bool) -> HardwareVerificationResult:
        """Verify weapon system ready state"""
        current_time = pytime.time()

        if ready_state and self_test_passed:
            result = HardwareVerificationResult(
                component=HardwareComponent.WEAPON_SYSTEM,
                status=VerificationStatus.VERIFIED,
                timestamp=current_time
            )
        else:
            result = HardwareVerificationResult(
                component=HardwareComponent.WEAPON_SYSTEM,
                status=VerificationStatus.FAILED,
                timestamp=current_time,
                error_code=1005,
                error_message=f"Weapon ready: {ready_state}, self-test: {self_test_passed}"
            )

        self.hw_state.update_component(result)
        return result

    def verify_tracking_processor(self, latency_ms: float) -> HardwareVerificationResult:
        """Verify tracking processor latency"""
        current_time = pytime.time()

        if latency_ms <= self.MAX_TRACKING_LATENCY_MS:
            result = HardwareVerificationResult(
                component=HardwareComponent.TRACKING_PROCESSOR,
                status=VerificationStatus.VERIFIED,
                timestamp=current_time
            )
        else:
            result = HardwareVerificationResult(
                component=HardwareComponent.TRACKING_PROCESSOR,
                status=VerificationStatus.FAILED,
                timestamp=current_time,
                error_code=1006,
                error_message=f"Tracking latency {latency_ms:.0f}ms exceeds {self.MAX_TRACKING_LATENCY_MS}ms limit"
            )

        self.hw_state.update_component(result)
        return result

    def verify_ew_suite(self, operational: bool) -> HardwareVerificationResult:
        """Verify EW suite operational status"""
        current_time = pytime.time()

        if operational:
            result = HardwareVerificationResult(
                component=HardwareComponent.EW_SUITE,
                status=VerificationStatus.VERIFIED,
                timestamp=current_time
            )
        else:
            result = HardwareVerificationResult(
                component=HardwareComponent.EW_SUITE,
                status=VerificationStatus.FAILED,
                timestamp=current_time,
                error_code=1007,
                error_message="EW suite not operational"
            )

        self.hw_state.update_component(result)
        return result

    def verify_power_management(self, power_reserve_percent: float) -> HardwareVerificationResult:
        """Verify adequate power reserves"""
        current_time = pytime.time()

        if power_reserve_percent >= self.MIN_POWER_RESERVE_PERCENT:
            result = HardwareVerificationResult(
                component=HardwareComponent.POWER_MANAGEMENT,
                status=VerificationStatus.VERIFIED,
                timestamp=current_time
            )
        else:
            result = HardwareVerificationResult(
                component=HardwareComponent.POWER_MANAGEMENT,
                status=VerificationStatus.FAILED,
                timestamp=current_time,
                error_code=1008,
                error_message=f"Power reserve {power_reserve_percent:.0f}% below {self.MIN_POWER_RESERVE_PERCENT}% minimum"
            )

        self.hw_state.update_component(result)
        return result

    def run_full_verification(self,
                              gps_timing_error_ns: float,
                              rf_calibration_valid: bool,
                              rf_last_calibration: float,
                              antenna_failure_percent: float,
                              datalink_connected: bool,
                              datalink_quality: float,
                              weapon_ready: bool,
                              weapon_self_test: bool,
                              tracking_latency_ms: float,
                              ew_operational: bool,
                              power_reserve_percent: float) -> bool:
        """
        Run full hardware verification sequence

        Returns True only if ALL components pass verification.
        """
        self.verify_gps_timing(gps_timing_error_ns)
        self.verify_rf_sensors(rf_calibration_valid, rf_last_calibration)
        self.verify_antenna_array(antenna_failure_percent)
        self.verify_datalink(datalink_connected, datalink_quality)
        self.verify_weapon_system(weapon_ready, weapon_self_test)
        self.verify_tracking_processor(tracking_latency_ms)
        self.verify_ew_suite(ew_operational)
        self.verify_power_management(power_reserve_percent)

        return self.hw_state.is_fully_verified()

    def request_engagement(self, request: EngagementRequest) -> EngagementAuthorizationResult:
        """
        Request authorization for BVR precision engagement

        CRITICAL: Engagement is ONLY authorized if:
        1. All hardware verification passes
        2. Target CEP meets precision requirements
        3. Verification is current (not stale)
        """
        current_time = pytime.time()

        # Check hardware verification state
        if not self.hw_state.is_fully_verified(current_time):
            unverified = self.hw_state.get_unverified_components()
            failed = self.hw_state.get_failed_components()

            if failed:
                reason = f"HW VERIFICATION FAILED: {', '.join(f'{c.name}: {m}' for c, m in failed)}"
                authorization = EngagementAuthorization.DENIED_HW_FAILURE
            else:
                reason = f"HW NOT VERIFIED: {', '.join(c.name for c in unverified)}"
                authorization = EngagementAuthorization.PENDING_VERIFICATION

            result = EngagementAuthorizationResult(
                request=request,
                authorization=authorization,
                hw_verification_state=self.hw_state,
                reason=reason
            )
            self.authorization_log.append(result)
            return result

        # Check CEP requirement for precision engagement
        if request.estimated_cep > self.MAX_CEP_FOR_PRECISION_M:
            result = EngagementAuthorizationResult(
                request=request,
                authorization=EngagementAuthorization.NOT_AUTHORIZED,
                hw_verification_state=self.hw_state,
                reason=f"CEP {request.estimated_cep:.0f}m exceeds precision limit {self.MAX_CEP_FOR_PRECISION_M}m"
            )
            self.authorization_log.append(result)
            return result

        # Check for any degraded components
        degraded = [
            comp for comp, r in self.hw_state.components.items()
            if r.status == VerificationStatus.DEGRADED
        ]

        if degraded:
            authorization = EngagementAuthorization.AUTHORIZED_DEGRADED
            reason = f"AUTHORIZED (DEGRADED): {', '.join(c.name for c in degraded)} operating in degraded mode"
        else:
            authorization = EngagementAuthorization.AUTHORIZED
            reason = "ALL HARDWARE VERIFIED - ENGAGEMENT AUTHORIZED"

        result = EngagementAuthorizationResult(
            request=request,
            authorization=authorization,
            hw_verification_state=self.hw_state,
            reason=reason,
            authorized_at=current_time
        )
        self.authorization_log.append(result)
        return result

    def get_verification_summary(self) -> str:
        """Get human-readable verification summary"""
        lines = ["=" * 60, "HARDWARE VERIFICATION STATUS", "=" * 60]

        for component, result in self.hw_state.components.items():
            status_str = result.status.name
            if result.status == VerificationStatus.VERIFIED:
                status_str = f"[OK] {status_str}"
            elif result.status == VerificationStatus.FAILED:
                status_str = f"[FAIL] {status_str}: {result.error_message}"
            elif result.status == VerificationStatus.DEGRADED:
                status_str = f"[WARN] {status_str} ({result.degradation_percent:.1f}% degraded)"
            else:
                status_str = f"[--] {status_str}"

            lines.append(f"  {component.name:20s}: {status_str}")

        lines.append("-" * 60)
        if self.hw_state.is_fully_verified():
            lines.append("STATUS: ALL SYSTEMS VERIFIED - ENGAGEMENT AUTHORIZED")
        else:
            lines.append("STATUS: VERIFICATION INCOMPLETE - ENGAGEMENT NOT AUTHORIZED")
        lines.append("=" * 60)

        return "\n".join(lines)


def verify_bvr_engagement_hardware() -> BVREngagementController:
    """
    Factory function to create and initialize a verified BVR engagement controller

    Returns controller with hardware verification initialized.
    """
    controller = BVREngagementController()
    return controller


# Example usage and verification test
if __name__ == "__main__":
    print("BVR Precision Engagement Controller - Hardware Verification Test")
    print("=" * 70)

    # Create controller
    controller = BVREngagementController()

    # Attempt engagement WITHOUT verification
    print("\n[TEST 1] Attempt engagement without hardware verification:")
    request = EngagementRequest(
        request_id="ENG-001",
        target_track_id=1,
        target_position=np.array([50000, 0, 10000]),
        target_velocity=np.array([250, 0, 0]),
        estimated_cep=25.0,
        weapon_type="PL-15",
        timestamp=pytime.time()
    )

    result = controller.request_engagement(request)
    print(f"  Authorization: {result.authorization.name}")
    print(f"  Reason: {result.reason}")

    # Run full hardware verification
    print("\n[TEST 2] Running full hardware verification...")
    current_time = pytime.time()

    verified = controller.run_full_verification(
        gps_timing_error_ns=15.0,        # Good: < 20ns
        rf_calibration_valid=True,
        rf_last_calibration=current_time - 60,  # 1 minute ago
        antenna_failure_percent=1.5,     # Good: < 2%
        datalink_connected=True,
        datalink_quality=95.0,           # Good: > 90%
        weapon_ready=True,
        weapon_self_test=True,
        tracking_latency_ms=85.0,        # Good: < 120ms
        ew_operational=True,
        power_reserve_percent=25.0       # Good: > 15%
    )

    print(controller.get_verification_summary())

    # Attempt engagement WITH verification
    print("\n[TEST 3] Attempt engagement with hardware verification:")
    result = controller.request_engagement(request)
    print(f"  Authorization: {result.authorization.name}")
    print(f"  Reason: {result.reason}")

    # Test with failed component
    print("\n[TEST 4] Test with GPS timing failure:")
    controller2 = BVREngagementController()
    controller2.run_full_verification(
        gps_timing_error_ns=50.0,        # FAIL: > 20ns
        rf_calibration_valid=True,
        rf_last_calibration=current_time - 60,
        antenna_failure_percent=1.0,
        datalink_connected=True,
        datalink_quality=95.0,
        weapon_ready=True,
        weapon_self_test=True,
        tracking_latency_ms=85.0,
        ew_operational=True,
        power_reserve_percent=25.0
    )

    result = controller2.request_engagement(request)
    print(f"  Authorization: {result.authorization.name}")
    print(f"  Reason: {result.reason}")

    # Test with CEP too large
    print("\n[TEST 5] Test with CEP exceeding precision limit:")
    request_imprecise = EngagementRequest(
        request_id="ENG-002",
        target_track_id=2,
        target_position=np.array([60000, 5000, 11000]),
        target_velocity=np.array([240, 10, 0]),
        estimated_cep=150.0,  # FAIL: > 100m
        weapon_type="PL-15",
        timestamp=pytime.time()
    )

    result = controller.request_engagement(request_imprecise)
    print(f"  Authorization: {result.authorization.name}")
    print(f"  Reason: {result.reason}")

    print("\n" + "=" * 70)
    print("Hardware verification test complete.")
    print("BVR precision engagements require ALL hardware components verified.")
    print("=" * 70)
