#!/usr/bin/env python3
"""
Algorithm Documentation Runner

Executes all CAD algorithms and documents their mathematical basis,
inputs, outputs, complexity, and limitations for CI/CD logging.

Classification: UNCLASSIFIED // PUBLIC RELEASE
"""

import numpy as np
import json
import time
import sys
from datetime import datetime
from dataclasses import dataclass, asdict
from typing import List, Dict, Any

# Import local modules
from calculation_logger import (
    CalculationLogger, OutputFormat, init_logger
)
from pla_validated_cad import (
    generate_validated_ogive,
    generate_validated_cylinder,
    generate_validated_fin,
    create_df41_validated_spec,
    create_hq9b_validated_spec,
    create_j20_validated_spec,
    create_type055_validated_spec,
    generate_df41_validated_cad,
    generate_hq9b_validated_cad,
    generate_j20_validated_cad,
    generate_type055_validated_cad,
    LIMITATIONS_DOCUMENTATION
)


# =============================================================================
# ALGORITHM DEFINITIONS
# =============================================================================

ALGORITHMS = [
    {
        "name": "Tangent Ogive Nose Generation",
        "function": "generate_validated_ogive",
        "description": "Generates tangent ogive nose cone geometry for missile/aircraft radomes",
        "mathematical_basis": """
Tangent Ogive Equation:
-----------------------
The tangent ogive is defined by a circular arc tangent to the body at the base.

Ogive radius: ρ = (L² + R²) / (2R)

Where:
  L = nose length
  R = base radius
  ρ = radius of the generating arc

Surface profile: y(x) = √(ρ² - (L-x)²) + R - ρ

For x ∈ [0, L], this generates points (x, y) defining the ogive profile.

The 3D surface is generated by revolving this profile around the x-axis:
  P(x,θ) = (x, y(x)·cos(θ), y(x)·sin(θ))

Where θ ∈ [0, 2π]
""",
        "complexity": "O(n·m) where n=axial_resolution, m=circumferential_resolution",
        "limitations": [
            "Profile equation has singularity at x=0 when ρ² < L²",
            "Assumes circular cross-section (no elliptical ogives)",
            "Does not model blunt nose tips (requires spherical cap)",
            "Surface curvature accuracy depends on mesh resolution",
            "No validation against actual nose cone aerodynamics"
        ],
        "references": [
            "MIL-HDBK-762: Design of Aerodynamically Stabilized Free Rockets",
            "Crowell, G.A. 'The Descriptive Geometry of Nose Cones'",
            "NASA TN D-6996: Aerodynamic Characteristics of Bodies"
        ],
        "test_params": {"length": 1.0, "base_radius": 0.5, "resolution": 32}
    },
    {
        "name": "Cylinder/Frustum Generation",
        "function": "generate_validated_cylinder",
        "description": "Generates cylindrical or frustum (tapered cylinder) geometry",
        "mathematical_basis": """
Cylinder/Frustum Parametric Equations:
--------------------------------------
For a frustum with forward radius R_f and aft radius R_a:

Radius at position x: r(x) = R_f + (R_a - R_f) · (x/L)

Surface parametric form:
  P(x,θ) = (x, r(x)·cos(θ), r(x)·sin(θ))

Where:
  x ∈ [0, L] (axial position)
  θ ∈ [0, 2π] (circumferential angle)
  L = cylinder length

Surface area calculation:
  A = π(R_f + R_a)·√((R_f - R_a)² + L²) for frustum
  A = 2πRL for cylinder (R_f = R_a = R)

Volume calculation:
  V = (πL/3)(R_f² + R_f·R_a + R_a²) for frustum
  V = πR²L for cylinder
""",
        "complexity": "O(n·m) where n=axial_segments, m=circumferential_resolution",
        "limitations": [
            "Assumes circular cross-section",
            "No helical or twisted geometries",
            "End caps not automatically generated",
            "Taper is linear (no curved boat-tails)"
        ],
        "references": [
            "Standard parametric surface equations",
            "Computational geometry fundamentals"
        ],
        "test_params": {"length": 2.0, "forward_radius": 0.5, "aft_radius": 0.3, "resolution": 32}
    },
    {
        "name": "Fin/Control Surface Generation",
        "function": "generate_validated_fin",
        "description": "Generates missile/aircraft fin and control surface geometry",
        "mathematical_basis": """
Fin Geometry Parametric Equations:
----------------------------------
For a trapezoidal fin with sweep angle Λ:

Leading edge position at span y:
  x_LE(y) = y · tan(Λ)

Chord at span y:
  c(y) = c_root + (c_tip - c_root) · (y/b)

Where:
  c_root = root chord
  c_tip = tip chord
  b = fin span
  Λ = leading edge sweep angle

Trailing edge position:
  x_TE(y) = x_LE(y) + c(y)

Surface generation:
  Upper: z = +t/2
  Lower: z = -t/2
  Where t = fin thickness

Fin aspect ratio: AR = b²/S
Where S = fin planform area = b·(c_root + c_tip)/2
""",
        "complexity": "O(n) where n=spanwise_resolution",
        "limitations": [
            "Flat plate airfoil only (no NACA profiles)",
            "Constant thickness (no taper in thickness)",
            "No control surface deflection modeling",
            "Root/tip fairing not included",
            "No leading/trailing edge geometry"
        ],
        "references": [
            "NACA Report 921: Theoretical Symmetric Span Loading",
            "MIL-HDBK-1002: Structural Design Requirements"
        ],
        "test_params": {"root_chord": 0.5, "tip_chord": 0.2, "span": 0.4, "sweep_deg": 45, "thickness": 0.02}
    },
    {
        "name": "Physical Optics RCS Calculation",
        "function": "PhysicalOpticsRCSCalculator.calculate_rcs",
        "description": "Calculates Radar Cross Section using Physical Optics approximation",
        "mathematical_basis": """
Physical Optics RCS Approximation:
----------------------------------
The Physical Optics (PO) method approximates surface currents induced by
incident electromagnetic waves.

RCS Formula:
  σ = (4π/λ²) · |Σ(A_n · Γ · (n̂·k̂) · exp(j·2k·r_n·k̂))|²

Where:
  σ = radar cross section (m²)
  λ = wavelength = c/f
  A_n = area of triangle n
  Γ = reflection coefficient (material dependent)
  n̂ = surface normal unit vector
  k̂ = incident wave direction unit vector
  k = wave number = 2π/λ
  r_n = position vector to triangle centroid
  j = √(-1)

Summation is over all illuminated triangles (n̂·k̂ > 0).

Conversion to dBsm:
  σ_dBsm = 10·log₁₀(σ)

Valid when:
  - Object dimensions >> λ (high frequency limit)
  - Smooth surfaces (no sharp edges)
  - Not near grazing incidence
""",
        "complexity": "O(N) where N=number of triangles",
        "limitations": [
            "Valid only in high-frequency regime (object >> wavelength)",
            "Does not model edge diffraction",
            "Does not model creeping waves",
            "Does not model cavity resonances",
            "Assumes mono-static radar (Tx and Rx co-located)",
            "Material properties are simplified",
            "No multiple-bounce interactions"
        ],
        "references": [
            "Knott, E.F. 'Radar Cross Section Measurements'",
            "Ruck, G.T. 'Radar Cross Section Handbook'",
            "IEEE Standard 1502-2007: RCS Measurement"
        ],
        "test_params": {"frequency_ghz": 10.0, "azimuth_deg": 0, "elevation_deg": 0}
    },
    {
        "name": "Kill Probability Calculation",
        "function": "PkCalculation.calculate_pk",
        "description": "Calculates weapon kill probability with uncertainty quantification",
        "mathematical_basis": """
Kill Probability Chain:
-----------------------
Total Pk = P(detect) · P(track) · P(launch) · P(guidance) ·
           P(fuze) · P(warhead) · P(survive_CM) · P(network)

Each factor represents probability of success for that phase.

Salvo Kill Probability:
-----------------------
For N independent missiles:
  P(kill) = 1 - (1 - Pk_single)^N

With correlation factor ρ (missiles not fully independent):
  N_effective = 1 + (N-1)·(1-ρ)
  P(kill) = 1 - (1 - Pk_single)^N_effective

Multi-Layer Engagement:
-----------------------
For L layers, each with Pk_i:
  P(survive_all) = Π(1 - Pk_i) for i=1 to L
  P(killed) = 1 - P(survive_all)

Confidence Bounds:
-----------------
Lower bound: Product of pessimistic estimates
Upper bound: Product of optimistic estimates
Overall confidence: Geometric mean of individual confidences
""",
        "complexity": "O(1) for single calculation, O(N) for salvo, O(L) for multi-layer",
        "limitations": [
            "Independence assumption rarely holds perfectly",
            "Countermeasure effectiveness is highly uncertain",
            "Human factors not quantified",
            "Environmental effects parametric only",
            "Assumes stationary target during engagement",
            "No maneuver modeling"
        ],
        "references": [
            "RAND Corporation: Air Combat Modeling",
            "DOD Methodology for Pk Estimation",
            "Operations Research methods for combat analysis"
        ],
        "test_params": {"p_detect": 0.8, "p_track": 0.75, "p_guidance": 0.85}
    }
]


# =============================================================================
# MAIN EXECUTION
# =============================================================================

def run_algorithm_documentation():
    """Execute all algorithms and generate documentation"""

    # Initialize logger
    logger = init_logger(
        name="Algorithm-Documentation",
        output_formats=[OutputFormat.CONSOLE, OutputFormat.GITHUB_ACTIONS],
        log_file="algorithm_log.txt",
        verbose=True
    )

    results = {
        "timestamp": datetime.utcnow().isoformat(),
        "algorithms": [],
        "summary": {}
    }

    print("=" * 80)
    print("ALGORITHM DOCUMENTATION RUNNER")
    print("=" * 80)

    # Document each algorithm
    for algo_def in ALGORITHMS:
        print(f"\n{'─'*80}")
        print(f"ALGORITHM: {algo_def['name']}")
        print(f"{'─'*80}")

        with logger.log_algorithm(
            name=algo_def['name'],
            description=algo_def['description'],
            mathematical_basis=algo_def['mathematical_basis'],
            inputs=algo_def['test_params'],
            complexity=algo_def['complexity'],
            limitations=algo_def['limitations'],
            references=algo_def['references']
        ) as algo_ctx:

            # Run the algorithm if possible
            try:
                func_name = algo_def['function']
                params = algo_def['test_params']

                if func_name == "generate_validated_ogive":
                    mesh = generate_validated_ogive(
                        length=params['length'],
                        base_radius=params['base_radius'],
                        resolution=params['resolution']
                    )
                    algo_ctx.set_output("triangles", mesh.triangle_count)
                    algo_ctx.set_output("surface_area_m2", mesh.surface_area)
                    algo_ctx.set_output("valid_ratio", mesh.valid_triangle_count / max(1, mesh.triangle_count))

                elif func_name == "generate_validated_cylinder":
                    mesh = generate_validated_cylinder(
                        length=params['length'],
                        forward_radius=params['forward_radius'],
                        aft_radius=params['aft_radius'],
                        resolution=params['resolution']
                    )
                    algo_ctx.set_output("triangles", mesh.triangle_count)
                    algo_ctx.set_output("surface_area_m2", mesh.surface_area)

                elif func_name == "generate_validated_fin":
                    mesh = generate_validated_fin(
                        root_chord=params['root_chord'],
                        tip_chord=params['tip_chord'],
                        span=params['span'],
                        sweep_deg=params['sweep_deg'],
                        thickness=params['thickness']
                    )
                    algo_ctx.set_output("triangles", mesh.triangle_count)
                    algo_ctx.set_output("surface_area_m2", mesh.surface_area)

                else:
                    algo_ctx.set_output("status", "documentation_only")

            except Exception as e:
                logger.log_error(e, context=f"Running {algo_def['name']}")
                algo_ctx.set_output("error", str(e))

        # Store result
        results["algorithms"].append({
            "name": algo_def['name'],
            "description": algo_def['description'],
            "mathematical_basis": algo_def['mathematical_basis'],
            "complexity": algo_def['complexity'],
            "limitations": algo_def['limitations'],
            "references": algo_def['references']
        })

    # Generate summary
    results["summary"] = {
        "total_algorithms": len(ALGORITHMS),
        "geometry_algorithms": 3,
        "analysis_algorithms": 2,
        "total_limitations_documented": sum(len(a['limitations']) for a in ALGORITHMS)
    }

    # Finalize logger
    logger.finalize()

    # Write JSON report
    with open("algorithm_report.json", "w") as f:
        json.dump(results, f, indent=2)
    print("\nWrote: algorithm_report.json")

    # Write Markdown report
    md_report = logger.generate_markdown_report()

    # Add algorithm details to markdown
    md_lines = [md_report, "\n\n# Detailed Algorithm Documentation\n"]

    for algo in ALGORITHMS:
        md_lines.append(f"\n## {algo['name']}\n")
        md_lines.append(f"\n**Description:** {algo['description']}\n")
        md_lines.append(f"\n**Complexity:** {algo['complexity']}\n")
        md_lines.append("\n### Mathematical Basis\n")
        md_lines.append(f"```\n{algo['mathematical_basis']}\n```\n")
        md_lines.append("\n### Limitations\n")
        for lim in algo['limitations']:
            md_lines.append(f"- {lim}\n")
        md_lines.append("\n### References\n")
        for ref in algo['references']:
            md_lines.append(f"- {ref}\n")

    with open("algorithm_report.md", "w") as f:
        f.write("".join(md_lines))
    print("Wrote: algorithm_report.md")

    print("\n" + "=" * 80)
    print("ALGORITHM DOCUMENTATION COMPLETE")
    print("=" * 80)

    return results


if __name__ == "__main__":
    run_algorithm_documentation()
